version: '3'

services:
  jenkins:
    image: jenkins-arm64
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # mkdir ~/jenkins_vol
      - ~/jenkins_vol:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
